development: Add Ubuntu 24.04 AppArmor build fix
Ubuntu 24.04 restricts unprivileged user namespaces by default via
AppArmor. This causes BitBake workers to fail during the build with:

  PermissionError: [Errno 1] Operation not permitted
  bb.utils.disable_network: open("/proc/self/uid_map", "w")

Add a note to the dev environment setup doc explaining the required
sysctl fix so developers on Ubuntu 24.04 can build without hitting
this error.

Tested: Verified fix works on Ubuntu 24.04.1 LTS building
obmc-phosphor-image for the romulus machine target.

Change-Id: I7a667e8d60bc50c5115bbd60b4cc4566139862fd
Signed-off-by: AKash A007 <mirrorghost007@gmail.com>